### ISSUE TITLE
Validation data has overlaps, can't compute PSDS. Some labels are incorrect.

### ISSUE THREAD

**Issue by RicherMans** [turpaultn/DESED#55]
Hey there,
so I rewritten most of the baseline code for the DCASE2021 Challenge by myself and couldn't compute any PSDS related score.

The minimal code would be:

```python
from metrics import compute_psds_from_operating_points
psds_score_scenario1 = compute_psds_from_operating_points(
      None, # Will throw nontheless an erro since Ground truth is incorrect.
      'metadata/validation.tsv,
      'metadata/validation_duration.tsv',
      dtc_threshold=0.7,
      gtc_threshold=0.7,
      alpha_ct=0,
      alpha_st=1,
      save_dir='my_output_dir'.
)
```

the function above is defined in [here](https://github.com/DCASE-REPO/DESED_task/blob/21f28394dc8efbb40a69f75d738a59ffe09eb14a/desed_task/evaluation/evaluation_measures.py#L197)

Executing this throws an error:

```
psds_eval.psds.PSDSEvalError: The ground truth dataframe provided has intersecting events/labels for the same class.
```

After a short debug, I checked which files are causing the error. The four files are: 

```
Y2DF8mtDke8k_460.000_470.000.wav
Y5qx1HGIWJww_170.000_180.000.wav
Y6PwBeL3Abl8_60.000_70.000.wav
Y4trGKbbTmC4_30.000_40.000.wav
```

After checking the [metadata](https://github.com/turpaultn/DESED/blob/master/data/real/metadata/validation/validation.tsv), it seems that there are mistakes:

```
Y2DF8mtDke8k_460.000_470.000.wav	0.000	10.000	Frying
Y2DF8mtDke8k_460.000_470.000.wav	1.218	1.468	Dishes
Y2DF8mtDke8k_460.000_470.000.wav	1.893	2.263	Dishes
Y2DF8mtDke8k_460.000_470.000.wav	2.827	7.980	Speech
Y2DF8mtDke8k_460.000_470.000.wav	3.110	3.592	Dishes
Y2DF8mtDke8k_460.000_470.000.wav	*3.797*	*4.103*	Dishes
Y2DF8mtDke8k_460.000_470.000.wav	*3.797*	*4.492*	Dishes
Y2DF8mtDke8k_460.000_470.000.wav	*4.192*	*4.492*	Dishes
Y2DF8mtDke8k_460.000_470.000.wav	*7.980*	*8.230*	Dishes
Y2DF8mtDke8k_460.000_470.000.wav	*7.980*	*8.617*	Dishes
Y2DF8mtDke8k_460.000_470.000.wav	*8.367*	*8.617*	Dishes
Y2DF8mtDke8k_460.000_470.000.wav	8.797	10.000	Dishes
```

```
Y6PwBeL3Abl8_60.000_70.000.wav	0.000	1.318	Speech
Y6PwBeL3Abl8_60.000_70.000.wav	2.794	4.535	Speech
Y6PwBeL3Abl8_60.000_70.000.wav	4.129	4.453	Blender
Y6PwBeL3Abl8_60.000_70.000.wav	*4.724*	*5.335*	Blender
Y6PwBeL3Abl8_60.000_70.000.wav	*4.724*	*6.076*	Blender
Y6PwBeL3Abl8_60.000_70.000.wav	*5.400*	*6.076*	Blender
Y6PwBeL3Abl8_60.000_70.000.wav	6.635	9.118	Blender
Y6PwBeL3Abl8_60.000_70.000.wav	9.435	9.882	Blender
```

Should I just delete the "segmented" instances and keep the "long" instances i.e. in the example above, keep 4.724 - 6.076 ?

**Comment by turpaultn** [comment]
Hey there, 
Thanks for pointing it out, can you check on 2021 task 4 slack channel please ? (I don't succeed to upload them in this issue).

The metadata folder need to be updated in this repo, but I can't do it now, I'm out of office, I can do it next week.
Please tell me if you succeed to get the fixed TSV files on slack.

**Comment by RicherMans** [comment]
Hey there,
sorry I don't use slack.
I can wait until next week or whenever, it's not urgent, only slightly relevant to assert that results are comparable to the baseline.
Thanks for the answer.

**Comment by turpaultn** [comment]
This repo should have the right files, and should be different to what you're showing in this issue :
https://zenodo.org/record/4639776

I checked, but can you check it too please ?

**Comment by RicherMans** [comment]
Fixed the problem I had, thanks!
