### ISSUE TITLE
module 'desed' has no attribute 'download_real

### ISSUE THREAD

**Issue by visionchan** [turpaultn/DESED#57]
When I wanted to use desed to generate synthetic database, there have some Attribute Error: **_module 'desed' has no attribute 'download_real'_** and **_module 'desed' has no attribute 'download_desed_soundbank'_**

**Comment by turpaultn** [comment]
Which version of desed are you using ?

**Comment by Dxymiemiemie** [comment]
module 'desed' has no attribute 'get_backgroung_training'
hello, i check the package of desed but there is no model named this.
i use the way  : pip install --upgrade desed@git+https://github.com/turpaultn/DESED
to install the desed.
what‘s wrong with it? 
please tell me ,thanks!

**Comment by turpaultn** [comment]
Can you use the version 1.2.2 please ? :)

**Comment by Dxymiemiemie** [comment]
> ok, but my desed version is 1.3.7

**Comment by turpaultn** [comment]
I made a pull request to solve the problem 
Now we don't use get_backgroung_training anymore.

**Comment by Hassan-Zaib** [comment]
Hello there,



> Can you use version 1.2.2 please ? :)

Hello there,
there's no such distribution version found. i found the 1.2.4 but still the error persist

Need your guidance

**Comment by Hassan-Zaib** [comment]
> Hello there,
> 
> > Can you use version 1.2.2 please ? :)
> 
> Hello there, there's no such distribution version found. i found the 1.2.4 but still the error persist
> 
> Need your guidance

Done, Thankyou, desed version1.3.6 works instead of 1.3.7
