### ISSUE TITLE
Effective FP Rate not working for single class PSDS

### ISSUE THREAD

**Issue by niclas-b** [turpaultn/DESED#63]
Hello,

as I'm working an a single class sound event detection repository, I encountered the problem that using the effective false positive rate is corrupted and therefor both ROC curve and overall PSDS score cannot be computed (remain zero).

In psds.py, line 939 I changed 
`psd_roc = self._effective_tp_ratio(tpr_efpr_curve, alpha_st)` to `psd_roc = self._effective_tp_ratio(tpr_fpr_curve, alpha_st)`  to sovle the issue. It is possible in a single class problem because there are obviously no cross trigger effect that have to be accounted for, so that the the eFPR shoudl be the FPR actually. This does not seem to be the case. 

Edit: This is not solving the bug of course, it's just mitigating it.

**Comment by turpaultn** [comment]
Hello, 
You're on the DESED repo, I suggest you open an issue on the PSDS_eval repo here : https://github.com/DCASE-REPO/psds_eval/
Best, 
Nicolas
